# clusters/minikube/podinfo.yaml

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: podinfo
    version: 5.5.3
  values:
    image:
      repository: stefanprodan/podinfo
      tag: "*"
